# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_APPDRS_rcpp_hello`)
}

media_joao <- function(jp) {
    .Call(`_APPDRS_media_joao`, jp)
}

